### ISSUE TITLE
Recipe boxes in the ingredient search are not of equal size

### ISSUE THREAD

**Issue by saisameer1998** [SE-Fall-2024-Team-53/SE-Project-Recipe-Recommender#7]
![image](https://github.com/user-attachments/assets/750ee861-2a3b-4954-9939-9e52043f7d37)
The size of the boxes are different

**Comment by SwarajKaondal** [comment]
It varies since we can have multiple tags, steps or Ingredients for each recipe. We can either add a scrollable or truncate text if it exceeds the bounding box.

**Comment by saisameer1998** [comment]
Can use height: 100% and boxsizing to have every box of same size, it will look better if they are of same size

**Comment by saisameer1998** [comment]
Pushed the changes to fix the issue, Please review and merge the PR
