### ISSUE TITLE
Add pagination in ingredient search component

### ISSUE THREAD

**Issue by saisameer1998** [SE-Fall-2024-Team-53/SE-Project-Recipe-Recommender#8]
Adding pagination would make the UI faster as it doesn't have to display a lot of information at a time

**Comment by SwarajKaondal** [comment]
We can load data on scroll as well. We can show "Load More" at the end of the page. Whichever is easier to implement

**Comment by saisameer1998** [comment]
Pagination is already implemented in Diet Plan component, can refer to it there.

**Comment by saisameer1998** [comment]
Pushed the changes to add the pagination, Please review and merge the PR
